version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: freecompute-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - freecompute

  loki:
    image: grafana/loki:2.9.3
    container_name: freecompute-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - ./data/loki:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - freecompute

  grafana:
    image: grafana/grafana:latest
    container_name: freecompute-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-FreeCompute2024!Secure}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - freecompute
    depends_on:
      - prometheus
      - loki

  promtail:
    image: grafana/promtail:2.9.3
    container_name: freecompute-promtail
    restart: unless-stopped
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - freecompute
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    container_name: freecompute-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - freecompute

networks:
  freecompute:
    name: monitoring-network
