version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: freecompute-nginx
    restart: unless-stopped
    volumes:
      - ../dashboard:/usr/share/nginx/html:ro
      - ./nginx/nginx-minimal.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT:-8080}:80"
    networks:
      - freecompute

networks:
  freecompute:
    name: freecompute-network
    driver: bridge
